//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Livraria da Folha é uma unidade de negócios do Grupo Folha, que publica a Folha de S.Paulo..
        /// </summary>
        internal static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosso objetivo é informar o leitor sobre os principais títulos do mercado,com notas sobre lançamentos, reimpressões e promoções exclusivas. Uma equipe de redatores especializada é responsável por analisar e sugerir os melhores livros disponíveis em nosso extenso catálogo. Um rico e detalhado sistema de busca facilita a pesquisa e a localização dos livros em todas as áreas àsquais possam estar relacionados. A Livraria da Folha também oferece produtos em DVD, Blu-Ray e Games, com páginas exclusivas que listam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Texto2 {
            get {
                return ResourceManager.GetString("Texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Livraria da Folha também oferece produtos em DVD, Blu-Ray e Games, com páginas exclusivas que listam os melhores filmes, séries televisivas e jogos para videogames e PC. Uma livraria onde você encontra informação fácil, segura e com rapidez. Nosso objetivo é informar o leitor sobre os principais títulos do mercado,com notas sobre lançamentos, reimpressões e promoções exclusivas. Uma equipe de redatores especializada é responsável por analisar e sugerir os melhores livros disponíveis em nosso extenso catál [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Texto3 {
            get {
                return ResourceManager.GetString("Texto3", resourceCulture);
            }
        }
    }
}
